const $=s=>document.querySelector(s);let loginId=null,relayId=null,relayEnabled=false;
const API_URL=(window.RELAYDESK_API_URL||'').replace(/\/$/,'');
let panelUser=localStorage.getItem('relaydesk_user')||'';
let panelPass=localStorage.getItem('relaydesk_pass')||'';
if(!panelUser) panelUser=prompt('Control-panel username','admin')||'';
if(!panelPass) panelPass=prompt('Control-panel password')||'';
localStorage.setItem('relaydesk_user',panelUser);localStorage.setItem('relaydesk_pass',panelPass);
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)};
async function api(path,options={}){const r=await fetch(API_URL+path,{headers:{'Content-Type':'application/json','Authorization':'Basic '+btoa(panelUser+':'+panelPass),...(options.headers||{})},...options});const data=await r.json().catch(()=>({detail:'Unexpected server response'}));if(!r.ok)throw new Error(data.detail||'Request failed');return data}
async function refresh(){try{const d=await api('/api/status');const tg=d.telegram;const destinations=$('#messageDestination');const chosen=destinations.value;const options=d.relays.map(r=>({id:String(r.id),label:r.name+' → '+r.destination_link}));const signature=JSON.stringify(options);if(destinations.dataset.signature!==signature){destinations.replaceChildren(...options.map(r=>new Option(r.label,r.id)));destinations.dataset.signature=signature;if(options.some(r=>r.id===chosen))destinations.value=chosen;}$('#connectionBadge').classList.toggle('live',tg.connected);$('#connectionBadge span').textContent=tg.connected?(tg.profile?.name||tg.profile?.username||'Telegram connected'):'Telegram not connected';$('#telegramSetup').classList.toggle('connected',tg.connected);const relay=d.relays[0];if(relay){relayId=relay.id;relayEnabled=!!relay.enabled;$('#relayName').value=relay.name;$('#sourceLink').value=relay.source_link;$('#destinationLink').value=relay.destination_link;$('#toggleRelay').textContent=relayEnabled?'Stop relay':'Start relay';$('#toggleRelay').classList.toggle('danger',relayEnabled)}$('#deliveredCount').textContent=d.stats.delivered||0;$('#failedCount').textContent=d.stats.failed||0;$('#relayCount').textContent=d.relays.length;const job=relayId&&tg.jobs?.[relayId];const importing=!!job?.running;$('#jobProgress').classList.toggle('hidden',!job);$('#cancelImport').classList.toggle('hidden',!importing);$('#importAll').disabled=importing;$('#importTest').disabled=importing;if(job)$('#jobProgress b').textContent=job.message+` · ${job.delivered} delivered · ${job.failed} failed`;await loadActivity()}catch(e){toast(e.message)}}
$('#sendCode').onclick=async()=>{try{const d=await api('/api/auth/request-code',{method:'POST',body:JSON.stringify({api_id:+$('#apiId').value,api_hash:$('#apiHash').value.trim(),phone:$('#phone').value.trim()})});loginId=d.login_id;$('#verifyBox').classList.remove('hidden');toast('Telegram sent your verification code')}catch(e){toast(e.message)}};
$('#confirmCode').onclick=async()=>{try{const d=await api('/api/auth/confirm',{method:'POST',body:JSON.stringify({login_id:loginId,code:$('#loginCode').value.trim()||null,password:$('#twoFactor').value||null})});if(d.needs_password){$('#passwordWrap').classList.remove('hidden');toast('Enter your Telegram two-step password');return}toast('Telegram connected successfully');await refresh()}catch(e){toast(e.message)}};
function pair(){return{source_link:$('#sourceLink').value.trim(),destination_link:$('#destinationLink').value.trim()}}
$('#checkLinks').onclick=async()=>{try{const d=await api('/api/groups/check',{method:'POST',body:JSON.stringify(pair())});$('#pairResult').innerHTML=`✓ Found <b>${d.source.title}</b> → <b>${d.destination.title}</b>`;$('#pairResult').classList.remove('hidden');toast('Both Telegram groups are reachable')}catch(e){toast(e.message)}};
$('#saveRelay').onclick=async()=>{try{const d=await api('/api/relays',{method:'POST',body:JSON.stringify({id:relayId,name:$('#relayName').value.trim()||'My relay',...pair(),import_media:true})});relayId=d.id;toast('Group connection saved');await refresh()}catch(e){toast(e.message)}};
async function startImport(limit){if(!relayId){toast('Save the group connection first');return}if(limit===0&&!confirm('Import every visible old post now? Large groups can take time.'))return;try{await api(`/api/relays/${relayId}/import`,{method:'POST',body:JSON.stringify({limit})});toast('Historical import started');await refresh()}catch(e){toast(e.message)}}
$('#importAll').onclick=()=>startImport(0);$('#importTest').onclick=()=>startImport(Math.max(1,+$('#testCount').value||10));
$('#cancelImport').onclick=async()=>{if(!relayId)return;try{const d=await api(`/api/relays/${relayId}/import/stop`,{method:'POST'});toast(d.message);await refresh()}catch(e){toast(e.message)}};
$('#newOnly').onclick=async()=>{if(!relayId){toast('Save the group connection first');return}if(!confirm('Stop importing old posts, skip everything already in the old group, and monitor only posts made after now?'))return;try{const d=await api(`/api/relays/${relayId}/new-only`,{method:'POST'});toast(d.message);await refresh()}catch(e){toast(e.message)}};
$('#toggleRelay').onclick=async()=>{if(!relayId){toast('Save the group connection first');return}try{await api(`/api/relays/${relayId}/${relayEnabled?'stop':'start'}`,{method:'POST'});toast(relayEnabled?'Relay stopped':'24/7 relay started');await refresh()}catch(e){toast(e.message)}};
async function loadActivity(){const d=await api('/api/activity?limit=100');const box=$('#activityList');if(!d.items.length){box.innerHTML='<p class="empty">No delivery activity yet.</p>';return}const icon={text:'✎',photo:'▧',video:'▶',voice:'◉',file:'▤',system:'⚙'};box.innerHTML=d.items.map(x=>`<div class="activity-item ${x.status==='delivered'?'ok':'fail'}"><span class="type">${icon[x.kind]||'⌁'}</span><p><b>${x.relay_name} · ${x.kind}</b><small>Source post #${x.source_message_id}${x.error?' · '+escapeHtml(x.error):''}</small></p><time>${x.status}</time></div>`).join('')}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
$('#refresh').onclick=refresh;refresh();setInterval(refresh,5000);

$('#sendOwnerMessage').onclick=async()=>{
 const id=$('#messageDestination').value,text=$('#ownerMessage').value;
 if(!id){toast('Save a group connection first');return}
 if(!text.trim()){toast('Write your message first');return}
 const button=$('#sendOwnerMessage');button.disabled=true;button.textContent='Sending…';
 $('#ownerMessageStatus').textContent='Sending to the selected group…';
 try{const d=await api(`/api/relays/${id}/message`,{method:'POST',body:JSON.stringify({text})});$('#ownerMessageStatus').textContent=d.message;$('#ownerMessage').value='';toast(d.message)}
 catch(e){$('#ownerMessageStatus').textContent='Delivery could not be confirmed. Check your group before sending again. '+e.message}
 finally{button.disabled=false;button.textContent='Send to group'}
};
