const $=s=>document.querySelector(s);let loginId=null,relayId=null,relayEnabled=false;
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)};
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({detail:'Unexpected server response'}));if(!r.ok)throw new Error(data.detail||'Request failed');return data}
async function refresh(){try{const d=await api('/api/status');const tg=d.telegram;$('#connectionBadge').classList.toggle('live',tg.connected);$('#connectionBadge span').textContent=tg.connected?(tg.profile?.name||tg.profile?.username||'Telegram connected'):'Telegram not connected';$('#telegramSetup').classList.toggle('connected',tg.connected);const relay=d.relays[0];if(relay){relayId=relay.id;relayEnabled=!!relay.enabled;$('#relayName').value=relay.name;$('#sourceLink').value=relay.source_link;$('#destinationLink').value=relay.destination_link;$('#toggleRelay').textContent=relayEnabled?'Stop relay':'Start relay';$('#toggleRelay').classList.toggle('danger',relayEnabled)}$('#deliveredCount').textContent=d.stats.delivered||0;$('#failedCount').textContent=d.stats.failed||0;$('#relayCount').textContent=d.relays.length;const job=relayId&&tg.jobs?.[relayId];$('#jobProgress').classList.toggle('hidden',!job?.running);if(job)$('#jobProgress b').textContent=job.message+` · ${job.delivered} delivered · ${job.failed} failed`;await loadActivity()}catch(e){toast(e.message)}}
$('#sendCode').onclick=async()=>{try{const d=await api('/api/auth/request-code',{method:'POST',body:JSON.stringify({api_id:+$('#apiId').value,api_hash:$('#apiHash').value.trim(),phone:$('#phone').value.trim()})});loginId=d.login_id;$('#verifyBox').classList.remove('hidden');toast('Telegram sent your verification code')}catch(e){toast(e.message)}};
$('#confirmCode').onclick=async()=>{try{const d=await api('/api/auth/confirm',{method:'POST',body:JSON.stringify({login_id:loginId,code:$('#loginCode').value.trim()||null,password:$('#twoFactor').value||null})});if(d.needs_password){$('#passwordWrap').classList.remove('hidden');toast('Enter your Telegram two-step password');return}toast('Telegram connected successfully');await refresh()}catch(e){toast(e.message)}};
function pair(){return{source_link:$('#sourceLink').value.trim(),destination_link:$('#destinationLink').value.trim()}}
$('#checkLinks').onclick=async()=>{try{const d=await api('/api/groups/check',{method:'POST',body:JSON.stringify(pair())});$('#pairResult').innerHTML=`✓ Found <b>${d.source.title}</b> → <b>${d.destination.title}</b>`;$('#pairResult').classList.remove('hidden');toast('Both Telegram groups are reachable')}catch(e){toast(e.message)}};
$('#saveRelay').onclick=async()=>{try{const d=await api('/api/relays',{method:'POST',body:JSON.stringify({id:relayId,name:$('#relayName').value.trim()||'My relay',...pair(),import_media:true})});relayId=d.id;toast('Group connection saved');await refresh()}catch(e){toast(e.message)}};
async function startImport(limit){if(!relayId){toast('Save the group connection first');return}if(limit===0&&!confirm('Import every visible old post now? Large groups can take time.'))return;try{await api(`/api/relays/${relayId}/import`,{method:'POST',body:JSON.stringify({limit})});toast('Historical import started');await refresh()}catch(e){toast(e.message)}}
$('#importAll').onclick=()=>startImport(0);$('#importTest').onclick=()=>startImport(Math.max(1,+$('#testCount').value||10));
$('#toggleRelay').onclick=async()=>{if(!relayId){toast('Save the group connection first');return}try{await api(`/api/relays/${relayId}/${relayEnabled?'stop':'start'}`,{method:'POST'});toast(relayEnabled?'Relay stopped':'24/7 relay started');await refresh()}catch(e){toast(e.message)}};
async function loadActivity(){const d=await api('/api/activity?limit=100');const box=$('#activityList');if(!d.items.length){box.innerHTML='<p class="empty">No delivery activity yet.</p>';return}const icon={text:'✎',photo:'▧',video:'▶',voice:'◉',file:'▤',system:'⚙'};box.innerHTML=d.items.map(x=>`<div class="activity-item ${x.status==='delivered'?'ok':'fail'}"><span class="type">${icon[x.kind]||'⌁'}</span><p><b>${x.relay_name} · ${x.kind}</b><small>Source post #${x.source_message_id}${x.error?' · '+escapeHtml(x.error):''}</small></p><time>${x.status}</time></div>`).join('')}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
$('#refresh').onclick=refresh;refresh();setInterval(refresh,5000);
